task :local_run, [:git_reference] => ['tmp/working_clone'] do |name, args|
  Dir.chdir 'tmp/working_clone' do
    system "git checkout #{args.git_reference}"
    system 'bundle install'
    system 'rspec --format=json --out=json.out'
  end
end

directory 'tmp/working_clone' do
  system 'git clone git@github.com:18F/identity-idp.git tmp/working_clone'
end
