#!/bin/bash
export COVERAGE=1
bundle exec rspec --profile=10 spec/blueprints >test-hacking/blueprints.out 2>&1
bundle exec rspec --profile=10 spec/components >test-hacking/components.out 2>&1
bundle exec rspec --profile=10 spec/config >test-hacking/config.out 2>&1
bundle exec rspec --profile=10 spec/controllers >test-hacking/controllers.out 2>&1
bundle exec rspec --profile=10 spec/decorators >test-hacking/decorators.out 2>&1
bundle exec rspec --profile=10 spec/fixtures >test-hacking/fixtures.out 2>&1
bundle exec rspec --profile=10 spec/forms >test-hacking/forms.out 2>&1
bundle exec rspec --profile=10 spec/helpers >test-hacking/helpers.out 2>&1
bundle exec rspec --profile=10 spec/rb >test-hacking/rb.out 2>&1
bundle exec rspec --profile=10 spec/javascripts >test-hacking/javascripts.out 2>&1
bundle exec rspec --profile=10 spec/jobs >test-hacking/jobs.out 2>&1
bundle exec rspec --profile=10 spec/lib >test-hacking/lib.out 2>&1
bundle exec rspec --profile=10 spec/mailers >test-hacking/mailers.out 2>&1
bundle exec rspec --profile=10 spec/models >test-hacking/models.out 2>&1
bundle exec rspec --profile=10 spec/policies >test-hacking/policies.out 2>&1
bundle exec rspec --profile=10 spec/presenters >test-hacking/presenters.out 2>&1
bundle exec rspec --profile=10 spec/requests >test-hacking/requests.out 2>&1
bundle exec rspec --profile=10 spec/routing >test-hacking/routing.out 2>&1
bundle exec rspec --profile=10 spec/scripts >test-hacking/scripts.out 2>&1
bundle exec rspec --profile=10 spec/services >test-hacking/services.out 2>&1
bundle exec rspec --profile=10 spec/views >test-hacking/views.out 2>&1
bundle exec rspec --profile=10 spec/features >test-hacking/features.out 2>&1
